app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
T43:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /T43

T44:
    resource: "@AppBundle/Resources/config/T44/routing.yml"
    prefix: /T44