app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix : /{_locale}/
    requirements:
        _locale: es|en
T43:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /T43

T44:
    resource: "@AppBundle/Resources/config/T44/routing.yml"
    prefix: /T44

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix : /{_locale}/
    requirements:
        _locale: es|en

contact:
    path:     /{_locale}/product/list/jjjjjjj
    defaults: { _controller: AppBundle:Product:list }
    requirements:
        _locale: es|en
